### ISSUE TITLE
Question: Spanish Ministry of Culture

### ISSUE THREAD

**Issue by pacoVela** [mvz/alexandria-book-collection-manager#102]
Just installed  and Spanish Ministry of Culture does not appear as provider. How could I add it? Is there a way to add it as Z39.50?

**Comment by mvz** [comment]
Hi @pacoVela I'm afraid the provider for the Spanish Ministry of Culture was removed because the site structure had changed. I'll take a look if it can be restored and made functional again.

**Comment by mvz** [comment]
I have decided not to update providers that are based on web scraping if they stop working due to site changes. Therefore this provider will not be restored.
