### ISSUE TITLE
crashed on run in gobject-introspection

### ISSUE THREAD

**Issue by majioa** [mvz/alexandria-book-collection-manager#19]
I've run

    $ alexandria

and got:

    -----------------------
    Alexandria just crashed
    -----------------------
    Timestamp: 2019-02-27 12:30:28 +0300  
    Message: <Gtk::ToggleAction#set_active>: the 0th argument must not nil: <is_active>
    Backtrace:
    /usr/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.2/lib/gobject-introspection/loader.rb:622:in `invoke'
    /usr/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.2/lib/gobject-introspection/loader.rb:622:in `block in define_method'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria       /ui/callbacks.rb:386:in `block in connect_signals'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/callbacks.rb:384:in `each'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/callbacks.rb:384:in `connect_signals'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/ui_manager.rb:98:in `setup_callbacks'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/ui_manager.rb:46:in `initialize'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/main_app.rb:59:in `new'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/main_app.rb:59:in `initialize'
    /usr/lib/ruby/singleton.rb:141:in `new'
    /usr/lib/ruby/singleton.rb:141:in `block in instance'
    /usr/lib/ruby/singleton.rb:139:in `synchronize'
    /usr/lib/ruby/singleton.rb:139:in `instance'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui.rb:42:in `start_main_app'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui.rb:54:in `main'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria.rb:50:in `main'
    /usr/bin/alexandria:60:in `<main>'
    Release: 0.7.2(0.7.2)
    Uname -a: Linux kgin.localdomain 4.9.71-std-def-alt0.M80P.1 #1 SMP Thu Dec 21 01:27:05 UTC 2017 x86_64 GNU/Linux
    --
    Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
    information, such as the description of the crash and the steps to reproduce it
    (if it's possible).

**Comment by mvz** [comment]
I'm not sure why, but it looks like alexandria loaded version 3.3.2 of gobject-introspection, even though version 0.7.2 depends on gobject-introspection version 3.2.1.

In any case, I have released version 0.7.3, which has updated dependencies and updates the call to `#set_active` to pass `false` instead of `nil`.
