### ISSUE TITLE
Crashed with 3.3.6/3.3.2 glib2 gem

### ISSUE THREAD

**Issue by majioa** [mvz/alexandria-book-collection-manager#20]
Crashed with 3.3.6/3.3.2 glib2 gem

I've got the following log:

    -----------------------
    Alexandria just crashed
    -----------------------
    Timestamp: 2019-04-03 12:28:46 +0300
    Message: <Gtk::TreeViewColumn#set_visible>: the 0th argument must not nil: <visible>
    Backtrace:
    /usr/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.6/lib/gobject-introspection    /loader.rb:616:in `invoke'
    /usr/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:616:in `invoke'
    /usr/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.6/lib/gobject-introspection/loader.rb:533:in `block in define_method'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/listview.rb:207:in `block in setup_listview_columns_visibility'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/listview.rb:206:in `each_index'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/listview.rb:206:in `setup_listview_columns_visibility'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/ui_manager.rb:78:in `setup_dependents'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/ui_manager.rb:40:in `initialize'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/main_app.rb:59:in `new'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui/main_app.rb:59:in `initialize'
    /usr/lib/ruby/singleton.rb:141:in `new'
    /usr/lib/ruby/singleton.rb:141:in `block in instance'
    /usr/lib/ruby/singleton.rb:139:in `synchronize'
    /usr/lib/ruby/singleton.rb:139:in `instance'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui.rb:42:in `start_main_app'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib/alexandria/ui.rb:54:in `main'
    /usr/lib/ruby/gems/2.5.0/gems/alexandria-book-collection-manager-0.7.3/lib   /alexandria.rb:36:in `main'
    /usr/bin/alexandria:47:in `<main>'
    Release: 0.7.3(0.7.3)
    Uname -a: Linux kgin.localdomain 4.9.71-std-def-alt0.M80P.1 #1 SMP Thu Dec 21 01:27:05 UTC 2017 x86_64 GNU/Linux
    --
    Please report this dump to 'http://www.github.com/mvz/alexandria-book-collection-manager/issues' with some additional
    information, such as the description of the crash and the steps to reproduce it
    (if it's possible).

Note: I have used the X forwarding over ssh to the target PC.

**Comment by jrmhaig** [comment]
I also got this error when trying this on a newly install Debian 10 machine. I have managed to get it running by creating a `Gemfile` containing:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'alexandria-book-collection-manager'
gem 'glib2', '= 3.2.1'
```

This has installed version 0.7.2 of `alexandria-book-collection-manager` instead of 0.7.3. However, this crashes almost immediately with:

```
/home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/dialogs/new_book_dialog.rb:87:in `setup_dialog_gui': 'Gtk::SELECTION_MULTIPLE' has been deprecated. Use 'Gtk::SelectionMode::MULTIPLE' or ':multiple'.
/home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/models/library.rb:276:in `extract_numbers': Nil ISBN
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/models/library.rb:293:in `valid_isbn?'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui/dialogs/new_book_dialog.rb:554:in `on_focus'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gtk3-3.2.1/lib/gtk3/builder.rb:51:in `call'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gtk3-3.2.1/lib/gtk3/builder.rb:51:in `block in connect_signal'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:110:in `invoke'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:110:in `block in define_singleton_method'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui.rb:49:in `start_gtk'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria/ui.rb:55:in `main'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/lib/alexandria.rb:50:in `main'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/alexandria-book-collection-manager-0.7.2/bin/alexandria:60:in `<top (required)>'
	 from /home/librarian/.rbenv/versions/2.6.5/bin/alexandria:23:in `load'
	 from /home/librarian/.rbenv/versions/2.6.5/bin/alexandria:23:in `<top (required)>'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	 from /home/librarian/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
	 from /home/librarian/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
	 from /home/librarian/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

```
