### ISSUE TITLE
Segfault on "import" (gobject-introspection again)

### ISSUE THREAD

**Issue by bloff** [mvz/alexandria-book-collection-manager#33]
Hi guys, I was looking at options to manage a small library at a local club. We have an excel file with part of the data, so I would like to import.

But when I click "import" Alexandria crashes with a segfault.

It may simply be a bug with the gobject-introspection ruby library. But then again maybe not.

Any way to mitigate this? If this doesn't happen to you, what version of gobject-introspection are you using?

The console output is attached: [error.txt](https://github.com/mvz/alexandria-book-collection-manager/files/3937228/error.txt)

**Comment by mvz** [comment]
Hi @bloff, the crash happens for me too. There's a fix in ruby-gnome for this (https://github.com/ruby-gnome/ruby-gnome/commit/e37fc3a0eb5a4ddb8376026db7bb394a9dc973a7), but it hasn't been released yet. In the mean time, I'll create a workaround.

**Comment by bloff** [comment]
Thank you Matijs :)

**Comment by mvz** [comment]
This was fixed in version 0.7.5.
