### ISSUE TITLE
Crash on export

### ISSUE THREAD

**Issue by piotrdrag** [mvz/alexandria-book-collection-manager#38]
Alexandria crashes when clicking the Export button in the exporting dialog. Here’s the log:

[alexandria crash on export.txt](https://github.com/mvz/alexandria-book-collection-manager/files/4605557/alexandria.crash.on.export.txt)

alexandria-0.7.4-1.fc32.1.noarch

**Comment by mvz** [comment]
Thanks @piotrdrag. I'm able to reproduce this on my own machine and will take a look.
