### ISSUE TITLE
How to update translations

### ISSUE THREAD

**Issue by piotrdrag** [mvz/alexandria-book-collection-manager#40]
I’d like to update the Polish translation, but I can’t make use of the Makefile in po/:

```
$ make
find: ‘../data’: No such file or directory
find: ‘../data’: No such file or directory
rm -f ./alexandria.pot
Updating PO template from Ruby files
make: rgettext: Command not found
make: *** [Makefile:15: alexandria.pot] Error 127
```

Is there a way to get a fresh .pot file for Alexandria?

**Comment by mvz** [comment]
It looks like the Makefile is a bit outdated: The rgettext program was renamed to rxgettext a long time ago.

**Comment by piotrdrag** [comment]
The whole internationalization infrastructure seems a bit outdated; for example, intltool is long unmaintained and gettext can now extract strings from .desktop files.

GNOME had a whole project to move to newer gettext features and drop intltool: https://wiki.gnome.org/Initiatives/GnomeGoals/GettextMigration
