### ISSUE TITLE
Double click on book title does not popup preference dialog with 0.7.5

### ISSUE THREAD

**Issue by mtasaka** [mvz/alexandria-book-collection-manager#86]
With 0.7.5 (with Fedora patches applied)

*  launch alexandria-0.7.5
*  at the right pane, select one book title and double click it

the book preference dialog does not popups, which worked with 0.7.4.  
Note that I have not tried vanilla 0.7.5 (i.e. without Feodra packages applied).

Reverting https://github.com/mvz/alexandria-book-collection-manager/commit/18bb7b253ae1fa87baa85f52dc090f8ab95f34c7 (i.e. https://github.com/mvz/alexandria-book-collection-manager/pull/31 ) workarounds this issue.

**Comment by mvz** [comment]
It seems this is already fixed in master. I'll see about releasing a new version soon.

**Comment by mvz** [comment]
I have just released version 0.7.6 where this bug should be fixed.

**Comment by mtasaka** [comment]
Okay, actually it seems fixed, although I don't know what commit  fixed indeed. But anyway thank you!

**Comment by mvz** [comment]
I think the fix is in 1359ef2455a36550e66b4730d10470930af31a02.
