### ISSUE TITLE
Crash when clicking Library → Export or Import

### ISSUE THREAD

**Issue by piotrdrag** [mvz/alexandria-book-collection-manager#92]
After the update to `alexandria-0.7.6-1.fc33.noarch`, I get a segmentation fault after clicking Export or Import from the Library menu.

Here’s the terminal output:

[alexandria crash on export.txt](https://github.com/mvz/alexandria-book-collection-manager/files/5540559/alexandria.crash.on.export.txt)

[alexandria crash on import.txt](https://github.com/mvz/alexandria-book-collection-manager/files/5540560/alexandria.crash.on.import.txt)

**Comment by mvz** [comment]
This should be fixed in version 0.7.7.

**Comment by piotrdrag** [comment]
Thank you!
